/* eslint-disable max-len */
export default {
  siteName: 'Socialize-starter',
  twitterHandle: '@storytellercz',
  'site.description': 'Socialize-starter.',
  'site.keywords': 'StorytellerCZ, Meteor.js, socialize',
  'site.logoAlt': 'Socialize-starter logo',
  mobileMenu: 'Mobile menu',
  'common.signin': 'Login',
  'common.signup': 'Register',
  'common.signout': 'Logout',
  'common.dashboard': 'Dashboard',
  'common.pm': 'Messages',
  'common.settings': 'Settings',
  'common.options': 'Options',
  'common.profile': 'Profile',
  'common.about': 'About us',
  'common.accessdenied': 'Access denied',
  'common.accessdenied.msg': 'You were not given permission to go here. If you should have access here, please contact the owner and tell them to double check the settings.',
  'common.loading': 'Loading...',
  'common.add': 'Add',
  'common.save': 'Save',
  'common.email': 'E-mail',
  'common.soon': 'Coming soon...',
  'common.search': 'Search',
  'common.search.do': 'Search',
  'common.searching': 'Searching...',
  'common.report': 'Report',
  'common.user': 'User',
  'common.users': 'Users',
  'common.showmore': 'Show more',
  'common.futurefeature.title': 'Future feature',
  'common.futurefeature.text': 'We are very sorry, but this feature is not available at this time. We are working hard to make it available as soon as possible.',
  'common.nothingfound': 'Nothing found',
  'common.news': 'News',
  'common.post': 'Post',
  'common.statistics': 'Statistics',
  'common.lang.select': 'Select language',
  'common.submit': 'Submit',
  'common.close': 'Close',
  'common.comment': 'Comment',
  'common.comments': 'Comments',
  404: 'Page not found',
  'search.users': 'Search for users',
  'search.user': 'Search for user',
  'common.help': 'Help',
  'common.or': 'or',
  'common.account.create': 'Create an account',
  'common.footer.tagline': 'Starter for social apps.',
  'common.legal.tos': 'Terms of Service',
  'common.legal.community': 'Community Guidelines',
  'common.legal.privacy': 'Privacy Policy',
  'common.legal.copyright': 'Copyright Agreement',
  'common.legal.disclaimer': '© {year} All rights reserved, all texts belong to their respective authors.',
  admin: 'Admin',
  goodbye: 'Thank you! See you again!',
  'common.feedback': 'Feedback',
  'common.createdOn': 'Created on {date, date, short}',
  'common.saved': 'Saved!',
  'common.saving': 'Saving...',
  'common.friends': 'Friends',
  confirm: 'Confirm',
  cancel: 'Cancel',
  processing: 'Processing...',
  'common.noData': 'No data',
  'common.offlineStatus': 'You are currently offline.',
  next: 'Next',
  'common.legal.tos.short': 'Terms',
  'common.legal.privacy.short': 'Privacy',
  male: 'Male',
  female: 'Female',
  'common.legal.effectiveAt': 'Effective from',
  select: 'Please select',
  'common.statusFailed': 'Failed to connect to the server.',
  'common.statusConnecting': 'Attempting to connect to the server... ({count, number})',
  'common.legal.guidelines': 'Community Guidelines',
  'common.legal.gdpr': 'GDPR',
  'common.legal.gdpr.long': 'General Data Protection Regulation',
  'common.publish': 'Publish',
  'common.publishAt': 'Publication date and time',
  copyrights: 'Copyrights',
  'copyrights.desc': 'The full text of Socialize-starter Copyrights Agreement.',
  'common.pagination': 'Pagination'
}
