/* eslint-disable max-len */
export default {
    siteName: 'Socialize-starter',
    twitterHandle: '@storytellercz',
    'site.description': 'Socialize-starter.',
    'site.keywords': 'StorytellerCZ, Meteor.js, socialize',
    'site.logoAlt': 'Socialize-starter logo',
    mobileMenu: 'Mobilní menu',
    'common.signin': 'Přihlásit se',
    'common.signup': 'Registrovat se',
    'common.signout': 'Odhlásit se',
    'common.dashboard': 'Přehled',
    'common.pm': 'Soukromé zprávy',
    'common.settings': 'Nastavení',
    'common.options': 'Možnosti',
    'common.profile': 'Profil',
    'common.about': 'O nás',
    'common.accessdenied': 'Přístup odmítnut',
    'common.accessdenied.msg': 'Nemáte přístupová práva do této oblasti.',
    'common.loading': 'Načítám...',
    'common.add': 'Přidat',
    'common.save': 'Uložit',
    'common.email': 'E-mail',
    'common.soon': 'Coming soon...',
    'common.search': 'Vyhledávání',
    'common.search.do': 'Vyhledat',
    'common.searching': 'Vyhledávám...',
    'common.report': 'Nahlásit',
    'common.user': 'Uživatel',
    'common.users': 'Uživatelé',
    'common.showmore': 'Zobrazit více',
    'common.futurefeature.title': 'Budoucí funkce',
    'common.futurefeature.text': 'Omlouváme se, ale tato funkcionalita je momentálně ve vývoji.',
    'common.nothingfound': 'Nic nenalezeno',
    'common.news': 'Novinky',
    'common.post': 'Post',
    'common.statistics': 'Statistics',
    'common.lang.select': 'Select language',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.comment': 'Comment',
    'common.comments': 'Comments',
    404: 'Stránka nebyla nalezena',
    'search.users': 'Search for users',
    'search.user': 'Search for user',
    'common.help': 'Help',
    'common.or': 'or',
    'common.account.create': 'Create an account',
    'common.footer.tagline': 'Starter for social apps.',
    'common.legal.tos': 'Terms of Service',
    'common.legal.community': 'Community Guidelines',
    'common.legal.privacy': 'Privacy Policy',
    'common.legal.copyright': 'Copyright Agreement',
    'common.legal.disclaimer': '© {year} Všechna práva vyhrazena, všechny texty patří jejich příslušným autorům.',
    admin: 'Administrátor',
    goodbye: 'Děkujeme! Těšíme na Vaší další návštěvu!',
    'common.feedback': 'Zpětná vazba',
    'common.createdOn': 'Created on {date, date, short}',
    'common.saved': 'Uloženo!',
    'common.saving': 'Saving...',
    'common.friends': 'Friends',
    confirm: 'Confirm',
    cancel: 'Cancel',
    processing: 'Processing...',
    'common.noData': 'No data',
    'common.offlineStatus': 'You are currently offline.',
    next: 'Další',
    'common.legal.tos.short': 'Podmínky',
    'common.legal.privacy.short': 'Soukromí',
    male: 'Muž',
    female: 'Žena',
    'common.legal.effectiveAt': 'Účinné od',
    select: 'Prosím vyberte',
    'common.statusFailed': 'Nepodařilo se připojit k serveru.',
    'common.statusConnecting': 'Pokouším se připojit k serveru... ({count, number})',
    'common.legal.guidelines': 'Pravidla komunity',
    'common.legal.gdpr': 'GDPR',
    'common.legal.gdpr.long': 'Obecné nařízení o ochraně údajů',
    'common.publish': 'Zveřejnit',
    'common.publishAt': 'Datum a čas zveřejnění',
    copyrights: 'Copyrights',
    'copyrights.desc': 'The full text of Socialize-starter Copyrights Agreement.'
};