/* eslint-disable max-len */
export default {
    siteName: 'Socialize-starter',
    twitterHandle: '@storyercz',
    'site.description': 'Socialize-starter.',
    'site.keywords': 'StorytellerCZ, Meteor.js, socialize',
    'site.logoAlt': 'ソーシャルスターターロゴ',
    mobileMenu: 'モバイル メニュー',
    'common.signin': 'ログイン',
    'common.signup': '会員登録',
    'common.signout': 'ログアウト',
    'common.dashboard': 'ダッシュボード',
    'common.pm': 'メッセージ',
    'common.settings': '設定',
    'common.options': 'オプション',
    'common.profile': 'プロフィール',
    'common.about': '私たちについて',
    'common.accessdenied': 'アクセス拒否されました',
    'common.accessdenied.msg': 'あなたはここに行く許可を与えられていません。もしあなたがここにアクセスできるはずなら、オーナーに連絡して設定を再確認するように伝えてください。',
    'common.loading': '読み込み中...',
    'common.add': '追加',
    'common.save': 'セーブ',
    'common.email': 'メール',
    'common.soon': 'もうすぐです。。。',
    'common.search': '探索',
    'common.search.do': '見附る',
    'common.searching': '検索中です。。。',
    'common.report': '報告する',
    'common.user': 'ユーザー',
    'common.users': 'ユーザー',
    'common.showmore': 'もっと見せる',
    'common.futurefeature.title': '今後の機能',
    'common.futurefeature.text': '大変申し訳ありませんが、この機能は現在のところ利用できません。できるだけ早く利用できるように努力しています。',
    'common.nothingfound': '何も見つかりません',
    'common.news': 'ニュース',
    'common.post': 'ポスト',
    'common.statistics': '統計',
    'common.lang.select': '言語を選択',
    'common.submit': '送信する',
    'common.close': '閉じる',
    'common.comment': 'コメント',
    'common.comments': 'コメント',
    404: 'ページ発見できません。',
    'search.users': 'ユーザーの検索',
    'search.user': 'ユーザーの検索',
    'common.help': 'ヘルプ',
    'common.or': '又は',
    'common.account.create': 'アカウントの作成',
    'common.footer.tagline': 'ソーシャルアプリのスターター。',
    'common.legal.tos': '利用規約',
    'common.legal.community': 'コミュニティ・ガイドライン',
    'common.legal.privacy': 'プライバシーポリシー',
    'common.legal.copyright': '著作権規約',
    'common.legal.disclaimer': '© {year} すべての文章の著作権は、それぞれの著者に帰属します。',
    admin: '管理者',
    goodbye: 'ありがとうございました！ またね！',
    'common.feedback': '意見',
    'common.createdOn': '{date, date, short}で作成',
    'common.saved': '保存されました',
    'common.saving': '保存しています',
    'common.friends': '友達',
    confirm: '確認',
    cancel: 'キャンセル',
    processing: '今処理中',
    'common.noData': 'データなし',
    'common.offlineStatus': 'あなたは現在オフラインです。',
    next: '次へ',
    'common.legal.tos.short': '条件',
    'common.legal.privacy.short': '通知',
    male: '男性',
    female: '女性',
    'common.legal.effectiveAt': '{date, date, medium}から有効',
    'common.legal.changelog': 'Changes in this version',
    select: '選択してください',
    'common.statusFailed': 'サーバーへの接続に失敗しました。',
    'common.statusConnecting': 'サーバーへの接続を試みています...({count, number})',
    'common.legal.guidelines': 'コミュニティ・ガイドライン',
    'common.legal.gdpr': 'GDPR',
    'common.legal.gdpr.long': '一般データ保護規則',
    'common.publish': '発行',
    'common.publishAt': '公開日時',
    copyrights: '著作権',
    'copyrights.desc': 'Socialize-starter著作権使用許諾契約書の全文を掲載しています。',
    'common.pagination': 'ページング',
    'errorLoading.explained': '申し訳ありません。読み込み中にエラーが発生しました。',
    'notVerified.msg': 'アカウントのメールアドレスは確認されていません。',
    'notVerified.verify': 'メールアドレスを確認してください。',
    'a11y.user.menu': 'ユーザーメニュー',
    'a11y.navigation': 'ナビ',
    'dashboard.profile': 'あなたのプロフィール'
};