export default {
    'homepage.welcome': 'Socialize-starterへようこそ！',
    'about.title': 'About Socialize-starter',
    'about.desc': 'Socialize-starter is skeleton for Meteor Framework with social features out of the box.',
    'about.text.1': 'Socialize-starter is a Meteor framework started that fully covers all features of the accounts system of Meteor and Socialize packages functionality. In addition it includes additional features to be GDPR compliant making this a great template to start your next app that requires social media like functionality.',
    'about.text.2': 'Socialize-starterは、Storytellerとしても知られるJan Dvořák氏の♥️で作成されました。',
    'copyrights.desc': 'Socialize-starter著作権使用許諾契約書の全文を掲載しています。',
    'privacy.desc': 'Socialize-starterのプライバシーポリシーの法的全文です。',
    'guidelines.desc': 'Community Guidelines of Socialize-starter.',
    'tos.desc': 'Full legal text of Terms of Service of Socialize-starter.',
    'homepage.intro': 'Start your Meteor app with the basics for users and social interactions.',
    'gdpr.title': 'GDPR コンプライアンス',
    'gdpr.desc': 'Socialize-starterは、EUのGDPR指令に準拠しています。',
    'gdpr.compliant': 'Socialize-starterはGDPR準拠です',
    'gdpr.compliant.text': 'Socialize-starterでは、2018年5月25日のGDPR施行に向けて、コードベースの様々なアップデートや変更を実施しました。',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'デジタルミレニアム著作権法(Digital Millennium Copyright Act)',
    'dmca.title': 'デジタルミレニアム著作権法(DMCA)ポリシー',
    'dmca.subtitle': '著作権紛争の方針',
    'dmca.step1.title': '著作権侵害の報告の手順',
    'dmca.step2.title': '適切な善意の侵害通知が指定された代理人によって受領された場合。',
    'dmca.step3.title': '指定代理店へのカウンター・ノーティスの提供手続きについて',
    'dmca.desc': '私たちは、著作権侵害を真摯に受け止めています。',
    'gdpr.access.title': 'アクセス権およびデータポータビリティの権利',
    'gdpr.access.desc': 'ユーザー設定では、自分のすべてのデータをエクスポートすることができます。このデータは、標準的なJSON形式になります。',
    'gdpr.forget.title': '設定を保存しない',
    'gdpr.forget.desc': 'すべてのアカウントは、ユーザー設定で削除することができます。データの中には、特に販売や紛争の対象となったものが保存されている場合があります。',
    'dmca.step1.desc1': '報告は2つのシナリオに分かれています。1. 内部財産（敷地内に存在する財産の敷地内での侵害）。2. 外部財産（敷地内に存在しない財産の敷地内での侵害）。',
    'dmca.step1.desc2': '内部のプロパティを報告するには、プロパティ上の報告ボタンを使用します。外部資産の侵害を報告するには、フィードバック画面を使用します。どちらの場合も、個人情報と、所有権を確認するための追加情報の提供が求められます。',
    'dmca.step1.desc3': '虚偽の請求をされますと、今後、請求ができなくなりますのでご注意ください。',
    'dmca.step2.desc1': 'レポートを受け取り次第、お客様の資格と所有権の主張を確認します。問題がなければ、主張の確認に進みます。主張が真実であると判断した場合、反論通知の決定または14日が経過するまで、侵害物件にアクセスできないようにし、その後削除します。',
    'dmca.step3.desc1': '苦情が受理されると、指定物件の所有者は14日間以内に反論の通知を提出します。指定代理店はその後、紛争の調査を行います。この段階での指定代理店の決定は最終的なものとなります。',
    'homepage.profile': 'Full user functionality',
    'homepage.profile.desc': 'Included all are all user related functions from Meteor',
    'homepage.social': 'Socialize',
    'homepage.social.desc': 'Socialize packages give your the basic functionality that you are used to from social media.'
};