export default {
    'settings.biography': '伝記',
    'settings.biography.placeholder': 'プロフィールに表示される自分のことを少し紹介します。',
    'settings.avatar.title': '画像',
    'settings.avatar.own': '尊像',
    'settings.avatar.upload': '画像を選択',
    'settings.email': 'メール',
    'settings.email.msg': 'お客様のアカウントに関連する電子メール',
    'settings.email.verified.false': '検証されていない',
    'settings.email.verified.true': '確認済みメール',
    'settings.email.add': 'メールを追加',
    'settings.languages.title': '言語設定',
    'settings.languages.notice': '現在、公式にサポートされている言語は英語のみです。その他の言語は、素晴らしいボランティアのおかげで利用可能ですが、まだ不完全な場合があります。',
    'settings.languages.join': 'よろしければ、Socialize-starter宙も翻訳してみてください。',
    'settings.name.title': '本名',
    'settings.name.given': '名',
    'settings.name.family': '苗字',
    'settings.username.change': '別名を変更',
    'settings.username.label': '別名',
    'settings.password.title': 'パスワードを変更する',
    'settings.password.current': '現在のパスワード',
    'settings.password.new': '新しいパスワード',
    'settings.password.repeat': '新しいパスワードをもう一度入力してください',
    'settings.password.nomatch': '新しいパスワードが一致しません。',
    'settings.password.reset': 'あなたのパスワードをリセット',
    'settings.password.resetSend': 'パスワードの再設定方法を記載したメールを送信しました。',
    'settings.socialConnectTitle': '他のサービスのアカウントとの連携',
    'settings.socialDisconnect': '切断する',
    'settings.socialConnect': '接続する',
    'settings.loginWith': '{service}でログイン ',
    'settings.connectTo': '{service}に接続する ',
    'settings.export.title': 'データのエクスポート',
    'settings.export.explain': 'これにより、私たちのデータベースに保存されているすべてのデータをjson形式で取得することができます。',
    'settings.export.submit': 'データのエクスポート',
    'settings.delete.title': 'アカウントを削除する',
    'settings.delete.warning': `警告：アカウントを削除すると、このアカウントへのアクセス権が失われ、元に戻すことはできません。ただし、公開された作品やコメントなどが自動的に削除されるわけではありません。詳しくは利用規約をご覧ください。`,
    'settings.delete.confirm': '念のため、確認しておきます。本当にアカウントを削除していいのか？',
    'settings.delete.cancel': '自分のアカウントを削除したくない',
    'settings.delete.submit': 'アカウントを削除します',
    'settings.legal.title': 'ユーザー同意契約',
    'settings.legal.explained': 'ここでは、様々な法的文書への同意を管理することができます。',
    'settings.name.private': '名前は非公開になります',
    'settings.emailSubscriptions.title': 'メール通知の設定',
    'settings.emailSubscriptions.explain': '当社からのお知らせメールを希望するものを選択してください。',
    'settings.emailSubscriptions.newsletter': '時折発行されるニュースレター',
    'settings.profile': 'プロファイル設定',
    'settings.account': 'アカウント設定',
    'settings.legal.export.download': 'あなたのデータをダウンロードする',
    'settings.legal.export.gathering': 'あなたのデータを収集しています。これにはしばらく時間がかかる場合があります。',
    'settings.gender.title': 'あなたの性別',
    'settings.gender.usage': 'This information will remain private. We use this data for platform analytics and in anonymized analytics.',
    'settings.age.title': 'あなたの年齢',
    'settings.age.explicit': '露骨な内容の表示（評価年齢21以上）',
    'settings.age.usage': 'This information will remain private. We are legally obliged to inquire about your age. We use this data for platform analytics, displaying content based on ratings and in anonymized analytics.',
    'settings.country.title': 'あなたの国',
    'settings.country.usage': 'We are legally obliged to inquire about your country in order to respond to government inquiries. We use this data for platform analytics and in anonymized analytics. If you wish you can display this information on your profile.',
    'settings.country.public': '自分の国を公開する',
    'settings.country.select': '国を選択してください',
    'settings.emailSubscriptions.newsletterTech': '開発者からのニュースレターが届くこともあります',
    'settings.emailSubscriptions.newsletterFeatures': '新機能に関する情報',
    'settings.emailNotifications.title': '通知',
    'settings.emailNotifications.pm': '新しいメッセージ',
    'settings.emailNotifications.newChapters': '新しい物語の章',
    'settings.resetPasswordEmailSend': 'パスワードをメールにリセットする方法の手順をお送りします。',
    'settings.theme.title': 'ウェブサイトの外観',
    'settings.theme.label': 'ウェブサイトのテーマ',
    'settings.theme.light': '白い',
    'settings.theme.dark': '黒い',
    'settings.links.title': 'あなたの他のウェブサイトへのリンク',
    'settings.links.description': 'これらのリンクは、あなたのプロフィールページに表示されます。',
    'settings.links.website': 'あなたの個人的なウェブサイト',
    'settings.links.social': 'その他のウェブサイト',
    // 2FA
    'settings.2fa.title': 'Two-factor authentication',
    'settings.2fa.explained': 'Two-factor authentication provides an additional layer of security for your account by adding an additional authentication step during login. This prevents malicious actors from gaining access to your account if your first login step is compromised.',
    'settings.2fa.otpTitle': 'OTP',
    'settings.2fa.otpExplained': 'Two-factor authentication with OTP code creates one-time password via authenticator applications (like Authy, Google/Microsoft Authenticator, etc.) that you enter on login.',
    'settings.2fa.otpModalAria': '2FA OTP method',
    'settings.2fa.otpAdd': 'Add 2FA OTP',
    'settings.2fa.confirmCode': 'Code that shows in your authentication application',
    'settings.2fa.svgAlt': 'QR code for authentication app',
    'settings.2fa.codeHeading': 'If you can\'t scan QR code, you can manually enter the following code:',
    'settings.2fa.instructionsTitle': 'Instructions',
    'settings.2fa.instructions1': 'Install and open authenticator application of your choice (Authy, Google/Microsoft Authenticator, FreeOTP, etc.)',
    'settings.2fa.instructions2': 'Select "Add account" (can be a visible "+" icon or can be hidden in a menu)',
    'settings.2fa.instructions3': 'Scan the QR code presented on the screen here or if not possible enter the code bellow.',
    'settings.2fa.instructions4': 'Type in the 6 numbers that appear on the screen into the input here to finish.',
    'settings.2fa.saved': 'Two-factor authentication successfully established!',
    'settings.2fa.disableOTP': 'Disable OTP two-factor authentication',
    // Web3
    'settings.web3.legend': 'Web3 wallet connection',
    'settings.web3.explained': 'You can connect your Web3 crypto wallet to you Literary Universe account. Once connected you will be able to login with your wallet and do even more things in the future as we expand our Web3 offering.',
    'settings.web3.connect': 'Connect your wallet',
    'settings.web3.address': 'Connected address: {address}',
    'settings.web3.verify': 'Sign your address',
    'settings.web3.verify.explained': 'To verify that this address belongs to you we will ask you to sign a message to ensure your ownership of the wallet.',
    'settings.web3.verified': 'Verified',
    'settings.web3.verificationMessage': 'Verifying user {username} for Literary Universe. Code: {code}',
    'settings.web3.unlink': 'Remove wallet',
    'settings.web3.linkingMessage': 'Please confirm that you want to link your wallet to Literary Universe. Code: {code}',
    'settings.web3.linkError': 'This address is already listed in our database and can\'t assigned!'
};