/* eslint-disable max-len */
export default {
    siteName: 'Socialize-starter',
    twitterHandle: '@storytellercz',
    'site.description': 'Socialize-starter.',
    'site.keywords': 'StorytellerCZ, Meteor.js, socialize',
    'site.logoAlt': 'Logo Socialize-starteru',
    mobileMenu: 'Mobilní menu',
    'common.signin': 'Přihlásit se',
    'common.signup': 'Registrovat se',
    'common.signout': 'Odhlásit se',
    'common.dashboard': 'Přehled',
    'common.pm': 'Soukromé zprávy',
    'common.settings': 'Nastavení',
    'common.options': 'Možnosti',
    'common.profile': 'Profil',
    'common.about': 'O nás',
    'common.accessdenied': 'Přístup odmítnut',
    'common.accessdenied.msg': 'Nemáte přístupová práva do této oblasti.',
    'common.loading': 'Načítám...',
    'common.add': 'Přidat',
    'common.save': 'Uložit',
    'common.email': 'E-mail',
    'common.soon': 'Připravujeme...',
    'common.search': 'Vyhledávání',
    'common.search.do': 'Vyhledat',
    'common.searching': 'Vyhledávám...',
    'common.report': 'Nahlásit',
    'common.user': 'Uživatel',
    'common.users': 'Uživatelé',
    'common.showmore': 'Zobrazit více',
    'common.futurefeature.title': 'Budoucí funkce',
    'common.futurefeature.text': 'Omlouváme se, ale tato funkcionalita je momentálně ve vývoji.',
    'common.nothingfound': 'Nic nenalezeno',
    'common.news': 'Novinky',
    'common.post': 'Příspěvek',
    'common.statistics': 'Statistiky',
    'common.lang.select': 'Vybrat jazyk',
    'common.submit': 'Odeslat',
    'common.close': 'Zavřít',
    'common.comment': 'Komentář',
    'common.comments': 'Komentáře',
    404: 'Stránka nebyla nalezena',
    'search.users': 'Vyhledat uživatele',
    'search.user': 'Vyhledat uživatele',
    'common.help': 'Pomoc',
    'common.or': 'nebo',
    'common.account.create': 'Založit účet',
    'common.footer.tagline': 'Starter pro sociální aplikace.',
    'common.legal.tos': 'Podmínky užívání',
    'common.legal.community': 'Pravidla komunity',
    'common.legal.privacy': 'Zásady ochrany osobních údajů',
    'common.legal.copyright': 'Prohlášení o autorských právech',
    'common.legal.disclaimer': '© {year} Všechna práva vyhrazena, všechny texty patří jejich příslušným autorům.',
    admin: 'Administrátor',
    goodbye: 'Děkujeme! Těšíme na Vaší další návštěvu!',
    'common.feedback': 'Zpětná vazba',
    'common.createdOn': 'Vytvořeno {date, date, short}',
    'common.saved': 'Uloženo!',
    'common.saving': 'Ukládám...',
    'common.friends': 'Přátelé',
    confirm: 'Potvrdit',
    cancel: 'Zrušit',
    processing: 'Probíhá zpracování...',
    'common.noData': 'Žádná data',
    'common.offlineStatus': 'Jste nyní v režimu offline.',
    next: 'Další',
    'common.legal.tos.short': 'Podmínky',
    'common.legal.privacy.short': 'Soukromí',
    male: 'Muž',
    female: 'Žena',
    'common.legal.effectiveAt': 'Effective from {date, date, medium}',
    select: 'Prosím vyberte',
    'common.statusFailed': 'Nepodařilo se připojit k serveru.',
    'common.statusConnecting': 'Pokouším se připojit k serveru... ({count, number})',
    'common.legal.guidelines': 'Pravidla komunity',
    'common.legal.gdpr': 'GDPR',
    'common.legal.gdpr.long': 'Obecné nařízení o ochraně údajů',
    'common.publish': 'Zveřejnit',
    'common.publishAt': 'Datum a čas zveřejnění',
    copyrights: 'Autorská práva',
    'copyrights.desc': 'Úplné znění dohody o autorských právech.',
    'common.pagination': 'Pagination'
};