export default {
    'homepage.welcome': 'Vítejte v Socialize-startéru!',
    'about.title': 'O Socialize-startéru',
    'about.desc': 'Socialize-starter je skeleton pro Meteor framefork s integrovanými sociálnimi prvky.',
    'about.text.1': 'Socialize-starter je skeleton pro Meteor framework, který plně pokrývá všechny funkce úživatelského systému Meteoru a socialize balíčků. Kromě toho obsahuje další funkce, které jsou v souladu s GDPR, což dělá skvělou šablonu pro spuštění vaší další aplikace, která vyžaduje například funkčnost sociálních sítí.',
    'about.text.2': 'Socialize-starter byl vytvořen s ♥️ Jan Dvořák, také známý jako Storyteller.',
    'copyrights.desc': 'Úplné znění dohody o autorských právech.',
    'privacy.desc': 'Úplný právní text Zásad ochrany osobních údajů.',
    'guidelines.desc': 'Komunitní pokyny pro Socialize-starter.',
    'tos.desc': 'Úplný právní text Podmínek služby Socialize-starter.',
    'homepage.intro': 'Začněte svou novou Meteor aplikaci se vším potřebným pro uživatelské účty a sociální interakce.',
    'gdpr.title': 'Soulad s GDPR',
    'gdpr.desc': 'Socialize-starter je v souladu s GDPR.',
    'gdpr.compliant': 'Socialize-starter je v souladu s GDPR',
    'gdpr.compliant.text': 'Socialize-starter realizoval různé aktualizace a změny své kódovací základny při přípravě prosazování GDPR 25. května 2018.',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'Digital Millennium Copyright Act',
    'dmca.title': 'Politika digitálního zákona o autorském právu (DMCA)',
    'dmca.subtitle': 'Zásady autorských práv pro spory',
    'dmca.step1.title': 'Postup hlášení porušení autorských práv.',
    'dmca.step2.title': 'Po obdržení řádného oznámení.',
    'dmca.step3.title': 'Postup pro podání odvolání a dalšího řízení.',
    'dmca.desc': 'Porušování autorských práv bereme vážně.',
    'gdpr.access.title': 'Právo na přístup a právo na přenositelnost údajů',
    'gdpr.access.desc': 'V uživatelském nastavení můžete exportovat všechna data. Tato data budou ve standardním formátu JSON.',
    'gdpr.forget.title': 'Právo na zapomenutí',
    'gdpr.forget.desc': 'Jakýkoli účet může být odstraněn v nastavení uživatele. Některá data mohou být zachována, zejména pokud byla předmětem prodeje a/nebo sporů.',
    'dmca.step1.desc1': 'Hlášení je rozděleno na dva scénáře. 1. Vnitřní majetek (porušení na stránce). 2. Externí majetek (porušení majetku, který na stránce neexistuje).',
    'dmca.step1.desc2': 'Hlášení vnitřního obsahu lze provést pomocí tlačítka hlášení u daného obsahu. Oznamování porušení vnějšího obsahu lze provést stejným způsobem. V obou případech budete požádáni o osobní údaje a další údaje, které nám umožní zkontrolovat vaše vlastnictví.',
    'dmca.step1.desc3': 'Vezměte prosím na vědomí, že falešná tvrzení povedou k vaší neschopnosti podávat žádosti v budoucnu.',
    'dmca.step2.desc1': 'Po obdržení vaší zprávy ověříme Vaše údaje a vlastnické nároky. Pokud je vše v pořádku, přistoupíme k ověření nároku. Pokud určíme nárok jako pravdivý, učiníme neoprávněné obsah nepřístupným, pokud nedojde k odvolání do 14 dní, po kterém bude tento majetek vymazán.',
    'dmca.step3.desc1': 'Po obdržení stížnosti bude mít vlastník určeného majetku 14 dní na podání odvolání. Jmenovaný agent pak přistoupí k vyšetřování sporu. Každé rozhodnutí jmenovaného agenta v této fázi bude konečné.',
    'homepage.profile': 'Kompletní funkce uživatele',
    'homepage.profile.desc': 'Zahrnuty je všechna uživatelská funkcionalita z Meteoru',
    'homepage.social': 'Socializace',
    'homepage.social.desc': 'Socialize balíčky dodávají základní funkcionalitu kterou znáte ze sociálních sítí.'
};