export default {
    'settings.biography': 'Biografie',
    'settings.biography.placeholder': 'Něco málo o Vás, pro zobrazení na Vašem profilu.',
    'settings.avatar.title': 'Avatar',
    'settings.avatar.own': 'Váš avatar',
    'settings.avatar.upload': 'Vyberte obrázek',
    'settings.email': 'E-maily',
    'settings.email.msg': 'E-maily spojené s Vaším účtem',
    'settings.email.verified.false': 'Neověřeno',
    'settings.email.verified.true': 'Ověřený e-mail',
    'settings.email.add': 'Přidat e-mail',
    'settings.languages.title': 'Jazyková nastavení',
    'settings.languages.notice': 'Angličtina je momentálně jediná oficiálně podporovaný jazyk. Ostatní jazyky jsou přístupné díky dobrovolníkům, ale nemusejí být úplné.',
    'settings.languages.join': 'Pokud nám chcete pomoci, můžete také přeložit Socialize-starter.',
    'settings.name.title': 'Skutečné jméno',
    'settings.name.given': 'Křestní jméno',
    'settings.name.family': 'Příjmení',
    'settings.username.change': 'Změnit uživatelské jméno',
    'settings.username.label': 'Uživatelské jméno',
    'settings.password.title': 'Změnit heslo',
    'settings.password.current': 'Současné heslo',
    'settings.password.new': 'Nové heslo',
    'settings.password.repeat': 'Zopakujte své nové heslo',
    'settings.password.nomatch': 'Hesla se neshodují!',
    'settings.password.reset': 'Resetovat heslo',
    'settings.password.resetSend': 'E-mail s instrukcemi pro resetování hesla byl odeslán!',
    'settings.socialConnectTitle': 'Propojte se s Vašimi účty z jiných služeb',
    'settings.socialDisconnect': 'Odpojit',
    'settings.socialConnect': 'Připojit',
    'settings.loginWith': 'Přihlásit se přes {service}',
    'settings.connectTo': 'Spojit s {service}',
    'settings.export.title': 'Export dat',
    'settings.export.explain': 'Získejte všechna Vaše data uložená v naší databázi ve formátu json.',
    'settings.export.submit': 'Exportovat data',
    'settings.delete.title': 'Smazat účet',
    'settings.delete.warning': `VAROVÁNÍ: Odstraněním vašeho účtu ztratíte přístup k tomuto účtu a
    neexistuje způsob, jak jej získat zpět. Všimněte si, že toto nemusí automaticky odstranit vaše publikované dílo,
    komentáře atd. Podrobnosti naleznete v podmínkách služby.`,
    'settings.delete.confirm': 'Pro potvrzení. Vážně chcete smazat váš účet?',
    'settings.delete.cancel': 'Nechci smazat svůj účet',
    'settings.delete.submit': 'Smazat můj účet',
    'settings.legal.title': 'Dohody o souhlasu uživatele',
    'settings.legal.explained': 'Zde můžete spravovat svůj souhlas s různými právními dokumenty.',
    'settings.name.private': 'Jméno bude soukromé',
    'settings.emailSubscriptions.title': 'Nastavení e-mailových oznámení',
    'settings.emailSubscriptions.explain': 'Vyberte, která e-mailová oznámení od nás chcete dostávat.',
    'settings.emailSubscriptions.newsletter': 'Příležitostný bulletin',
    'settings.profile': 'Nastavení profilu',
    'settings.account': 'Nastavení účtu',
    'settings.legal.export.download': 'Stáhnout data',
    'settings.legal.export.gathering': 'Shromažďuji Vaše data... To může chvíli trvat.',
    'settings.gender.title': 'Vaše pohlaví',
    'settings.gender.usage': 'Tato informace zůstanou soukromá. Tato data používáme pro analýzu platformy a anonymizované analýzy.',
    'settings.age.title': 'Váš věk',
    'settings.age.explicit': 'Zobrazit explicitní obsah (věkové hodnocení 21+)',
    'settings.age.usage': 'Tato informace zůstane soukromá. Jsme ze zákona povinni se ptát na váš věk. Používáme tento údaj pro analýzu platformy, zobrazujeme obsah na základě hodnocení a anonymizovaný analytik.',
    'settings.country.title': 'Vaše země',
    'settings.country.usage': 'Jsme ze zákona povinni se zeptat na vaši zemi, abychom mohli reagovat na vládní dotazy. Tento údaj používáme pro vylepšení systému a anonymizovanou analýzy. Pokud si přejete můžete zobrazit tento údaj na Vašem profilu.',
    'settings.country.public': 'Zobrazit Vaši zemi veřejně',
    'settings.country.select': 'Vyberte Vaši zemi',
    'settings.emailSubscriptions.newsletterTech': 'Příležitostný buletin od vývojářů',
    'settings.emailSubscriptions.newsletterFeatures': 'Informace o nových funkcích',
    'settings.emailNotifications.title': 'Upozornění',
    'settings.emailNotifications.pm': 'Nové zprávy',
    'settings.emailNotifications.newChapters': 'Nové kapitoly',
    'settings.resetPasswordEmailSend': 'Poslali jsme Vám pokyny, jak resetovat Vaše heslo na Váš e-mail.',
    'settings.theme.title': 'Vzhled stránky',
    'settings.theme.label': 'Motiv stránky',
    'settings.theme.light': 'Světlý',
    'settings.theme.dark': 'Tmavý',
    'settings.links.title': 'Odkazy na Vaše další webové stránky',
    'settings.links.description': 'Tyto odkazy se zobrazí na Vaší profilové stránce.',
    'settings.links.website': 'Vaše osobní stránka',
    'settings.links.social': 'Ostatní webové stránky',
    // 2FA
    'settings.2fa.title': 'Two-factor authentication',
    'settings.2fa.explained': 'Two-factor authentication provides an additional layer of security for your account by adding an additional authentication step during login. This prevents malicious actors from gaining access to your account if your first login step is compromised.',
    'settings.2fa.otpTitle': 'OTP',
    'settings.2fa.otpExplained': 'Two-factor authentication with OTP code creates one-time password via authenticator applications (like Authy, Google/Microsoft Authenticator, etc.) that you enter on login.',
    'settings.2fa.otpModalAria': '2FA OTP method',
    'settings.2fa.otpAdd': 'Add 2FA OTP',
    'settings.2fa.confirmCode': 'Code that shows in your authentication application',
    'settings.2fa.svgAlt': 'QR code for authentication app',
    'settings.2fa.codeHeading': 'If you can\'t scan QR code, you can manually enter the following code:',
    'settings.2fa.instructionsTitle': 'Instructions',
    'settings.2fa.instructions1': 'Install and open authenticator application of your choice (Authy, Google/Microsoft Authenticator, FreeOTP, etc.)',
    'settings.2fa.instructions2': 'Select "Add account" (can be a visible "+" icon or can be hidden in a menu)',
    'settings.2fa.instructions3': 'Scan the QR code presented on the screen here or if not possible enter the code bellow.',
    'settings.2fa.instructions4': 'Type in the 6 numbers that appear on the screen into the input here to finish.',
    'settings.2fa.saved': 'Two-factor authentication successfully established!',
    'settings.2fa.disableOTP': 'Disable OTP two-factor authentication',
    // Web3
    'settings.web3.legend': 'Web3 wallet connection',
    'settings.web3.explained': 'You can connect your Web3 crypto wallet to you Literary Universe account. Once connected you will be able to login with your wallet and do even more things in the future as we expand our Web3 offering.',
    'settings.web3.connect': 'Connect your wallet',
    'settings.web3.address': 'Connected address: {address}',
    'settings.web3.verify': 'Sign your address',
    'settings.web3.verify.explained': 'To verify that this address belongs to you we will ask you to sign a message to ensure your ownership of the wallet.',
    'settings.web3.verified': 'Verified',
    'settings.web3.verificationMessage': 'Verifying user {username} for Literary Universe. Code: {code}',
    'settings.web3.unlink': 'Remove wallet',
    'settings.web3.linkingMessage': 'Please confirm that you want to link your wallet to Literary Universe. Code: {code}',
    'settings.web3.linkError': 'This address is already listed in our database and can\'t assigned!'
};