/* eslint-disable max-len */
export default {
    siteName: 'Socialize-starter',
    twitterHandle: '@storytellercz',
    'site.description': 'Socialize-starter.',
    'site.keywords': 'StorytellerCZ, Meteor.js, socialize',
    'site.logoAlt': 'Socialize-starter logo',
    mobileMenu: 'モバイル メニュー',
    'common.signin': 'ログイン',
    'common.signup': '会員登録',
    'common.signout': 'ログアウト',
    'common.dashboard': 'ダッシュボード',
    'common.pm': 'メッセージ',
    'common.settings': '設定',
    'common.options': 'オプション',
    'common.profile': 'プロフィール',
    'common.about': '私たちについて',
    'common.accessdenied': 'アクセス拒否されました',
    'common.accessdenied.msg': 'You were not given permission to go here. If you should have access here, please contact the owner and tell them to double check the settings.',
    'common.loading': '読み込み中...',
    'common.add': 'Add',
    'common.save': 'セーブ',
    'common.email': 'メール',
    'common.soon': 'もうすぐです。。。',
    'common.search': 'Search',
    'common.search.do': 'Search',
    'common.searching': 'Searching...',
    'common.report': 'Report',
    'common.user': 'User',
    'common.users': 'Users',
    'common.showmore': 'Show more',
    'common.futurefeature.title': 'Future feature',
    'common.futurefeature.text': 'We are very sorry, but this feature is not available at this time. We are working hard to make it available as soon as possible.',
    'common.nothingfound': 'Nothing found',
    'common.news': 'ニュース',
    'common.post': 'Post',
    'common.statistics': 'Statistics',
    'common.lang.select': 'Select language',
    'common.submit': '送信する',
    'common.close': '閉じる',
    'common.comment': 'コメント',
    'common.comments': 'コメント',
    404: 'ページ発見できません。',
    'search.users': 'Search for users',
    'search.user': 'Search for user',
    'common.help': 'Help',
    'common.or': 'or',
    'common.account.create': 'Create an account',
    'common.footer.tagline': 'Starter for social apps.',
    'common.legal.tos': 'Terms of Service',
    'common.legal.community': 'Community Guidelines',
    'common.legal.privacy': 'Privacy Policy',
    'common.legal.copyright': 'Copyright Agreement',
    'common.legal.disclaimer': '© {year} All rights reserved, all texts belong to their respective authors.',
    admin: 'Admin',
    goodbye: 'Thank you! See you again!',
    'common.feedback': 'Feedback',
    'common.createdOn': 'Created on {date, date, short}',
    'common.saved': 'Saved!',
    'common.saving': 'Saving...',
    'common.friends': 'Friends',
    confirm: 'Confirm',
    cancel: 'Cancel',
    processing: 'Processing...',
    'common.noData': 'No data',
    'common.offlineStatus': 'You are currently offline.',
    next: 'Next',
    'common.legal.tos.short': 'Terms',
    'common.legal.privacy.short': 'Privacy',
    male: '男',
    female: '女',
    'common.legal.effectiveAt': 'Effective from',
    select: 'Please select',
    'common.statusFailed': 'Failed to connect to the server.',
    'common.statusConnecting': 'Attempting to connect to the server... ({count, number})',
    'common.legal.guidelines': 'Community Guidelines',
    'common.legal.gdpr': 'GDPR',
    'common.legal.gdpr.long': 'General Data Protection Regulation',
    'common.publish': 'Publish',
    'common.publishAt': 'Publication date and time',
    copyrights: 'Copyrights',
    'copyrights.desc': 'The full text of Socialize-starter Copyrights Agreement.'
};