export default {
    'homepage.welcome': 'Welcome to Socialize-starter!',
    'about.title': 'About Socialize-starter',
    'about.desc': 'Socialize-starter is skeleton for Meteor Framework with social features out of the box.',
    'about.text.1': 'Socialize-starter is a Meteor framework started that fully covers all features of the accounts system of Meteor and Socialize packages functionality. In addition it includes additional features to be GDPR compliant making this a great template to start your next app that requires social media like functionality.',
    'about.text.2': 'Socialize-starter has been created with ♥️ by Jan Dvořák, also known as Storyteller.',
    'copyrights.desc': 'The full text of Socialize-starter Copyrights Agreement.',
    'privacy.desc': 'Full legal text of Privacy Policy of Socialize-starter.',
    'guidelines.desc': 'Community Guidelines of Socialize-starter.',
    'tos.desc': 'Full legal text of Terms of Service of Socialize-starter.',
    'homepage.intro': 'Start your Meteor app with the basics for users and social interactions.',
    'gdpr.title': 'GDPR Compliance',
    'gdpr.desc': 'Socialize-starter is compliant with the EU GDPR directives.',
    'gdpr.compliant': 'Socialize-starter is GDPR Compliant',
    'gdpr.compliant.text': 'Socialize-starter has implemented various updates and changes to its codebase in preparation for GDPR enforcement on May 25th 2018.',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'Digital Millennium Copyright Act',
    'dmca.title': 'Digital Millennium Copyright Act (DMCA) Policy',
    'dmca.subtitle': 'Copyright Dispute Policy',
    'dmca.step1.title': 'Procedure for Reporting Copyright Infringements.',
    'dmca.step2.title': 'Once Proper Bona Fide Infringement Notification is Received by the Designated Agent.',
    'dmca.step3.title': 'Procedure to Supply a Counter-Notice to the Designated Agent.',
    'dmca.desc': 'We take copyright violations seriously.',
    'gdpr.access.title': 'Right of Access and Right of Data Portability',
    'gdpr.access.desc': 'In user settings you can export all your data. This data will be in standard JSON format.',
    'gdpr.forget.title': 'Right to be forgotten',
    'gdpr.forget.desc': 'Any account can be deleted via user settings. Some data might be preserved, especially if they have been subject to sale and/or disputes.',
    'dmca.step1.desc1': 'Reporting is split into two scenarios. 1. Internal property (infringement on site of property existing on site). 2. External property (infringement on site of property not existing on site).',
    'dmca.step1.desc2': 'Reporting internal property can be done via report button on the property. Reporting external property infringement can be done via feedback screen. In both cases you will be asked to provide personal details and additional details that will allow us to check your ownership.',
    'dmca.step1.desc3': 'Please note that making a false claims will result in your inability to file claims in the future.',
    'dmca.step2.desc1': 'Upon receiving your report we will verify your credentials and ownership claim. If everything is fine we will proceed to check claim. If we determine claim as true we will make the infringing property inaccessible until counter-notice determination or 14 days have passed after which it will be deleted.',
    'dmca.step3.desc1': 'Once a complaint has been received the owner of designated property will have 14 days to file a counter notice. Designated Agent will then proceed to investigate the dispute. Any decision by the Designated Agent at this stage will be final.',
    'homepage.profile': 'Full user functionality',
    'homepage.profile.desc': 'Included all are all user related functions from Meteor',
    'homepage.social': 'Socialize',
    'homepage.social.desc': 'Socialize packages give your the basic functionality that you are used to from social media.'
};